### ISSUE TITLE
ModuleNotFoundError: No module named 'metaflow.metadata'

### ISSUE THREAD

**Issue by talamb** [Netflix/metaflow-nflx-extensions#50]
My team is experiencing an issue with the latest metaflow update (2.12.29) it's giving this error

```
.tox/py310-sdist/lib/python3.10/site-packages/metaflow_extensions/netflix_ext/plugins/conda/conda_step_decorator.py:27: in <module>
    from metaflow.metadata import MetaDatum
E   ModuleNotFoundError: No module named 'metaflow.metadata'
```

We believe the issue is happening in [conda_step_decorator.py](https://github.com/Netflix/metaflow-nflx-extensions/blob/main/metaflow_extensions/netflix_ext/plugins/conda/conda_step_decorator.py). Reverting back to metaflow 2.12.25 fixes this issue

**Comment by romain-intel** [comment]
Oh, I am sorry. Yes, I changed something. Let me update this extension to fix it.

**Comment by romain-intel** [comment]
I will do this this evening if that is ok.

**Comment by talamb** [comment]
Thanks. That should be fine we've pinned it for now.

**Comment by romain-intel** [comment]
I've pushed all our changes from upstream here: #51. I'll let the tests run, verify that all is well and merge. Thanks for calling this out.
