### ISSUE TITLE
Upload version 1.2.3 to `conda-forge`

### ISSUE THREAD

**Issue by fumoboy007** [Netflix/metaflow-nflx-extensions#52]
The current version on [`conda-forge`](https://anaconda.org/conda-forge/metaflow-netflixext) is 1.2.2, which not compatible with Metaflow 2.12.29+.

**Comment by romain-intel** [comment]
Thanks. I noticed that for some reason it didn't publish. I'll try to fix it.

**Comment by romain-intel** [comment]
This should now be fixed. Thanks for letting me know.
